FROM node:20.9.0

WORKDIR /usr/src/app

COPY package*.json ./

# Install dependencies

RUN npm install

COPY . .

# Lets build the project

RUN npm run build

# Using nginx to serve the static files
FROM nginx:alpine

# Copy build files to nginx 
COPY --from=0 /usr/src/app/dist /usr/share/nginx/html

COPY nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]